# Generated by Django 3.0.5 on 2020-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Short Answer', 'Short Answer'), ('Paragraph', 'Paragraph')], default='Short Answer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fields', models.ManyToManyField(to='form.FormField')),
            ],
        ),
    ]
