# Generated by Django 3.0.5 on 2020-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200516_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='answer_link',
            field=models.URLField(null=True),
        ),
    ]
