# Generated by Django 3.0.5 on 2020-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200516_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='answer_link',
        ),
        migrations.AddField(
            model_name='form',
            name='answer_link_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
