# Generated by Django 3.0.5 on 2020-05-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20200517_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='answer',
            field=models.CharField(default='asd', max_length=2000),
            preserve_default=False,
        ),
    ]
